---
- name: Restart sshd service if httpd is running
  hosts: ansible1
  tasks:
    - name: Get httpd service status
      ansible.builtin.command: /usr/bin/systemctl is-active httpd
      ignore_errors: true
      register: result

    - name: Show result variable contents
      ansible.builtin.debug:
        msg: printing contents of the registered variable {{ result }}

    - name: Restart sshd service
      ansible.builtin.service:
        name: sshd
        state: restarted
      when: result.rc == 0
